import os


SECURITY_INTERVAL = os.getenv("SECURITY_INTERVAL", 90)
SECURITY_PASSWORD_SALT = os.getenv("SECURITY_SALT", "1am5u9erSEcr3T34")
SECURITY_REGISTERABLE = os.getenv("USER_REGISTRATION", False)
SECURITY_SEND_REGISTER_EMAIL = os.getenv("SECURITY_EMAIL", False)
SECURITY_USER_IDENTITY_ATTRIBUTES = ("username", "email")
